package org.aminesidki.postprep.mapper;

import org.aminesidki.postprep.entity.AppUser;
import org.aminesidki.postprep.dto.regular.AppUserDTO;
import org.aminesidki.postprep.repository.ArticleRepository;
import org.springframework.stereotype.Component;
import lombok.RequiredArgsConstructor;

/**
* Mapper for {@link org.aminesidki.postprep.entity.AppUser }
*/
@Component
@RequiredArgsConstructor
public class AppUserMapper {
    private final ArticleRepository articleRepository;

    public AppUser toEntity(AppUserDTO dto) {
        if (dto == null) {
            return null;
        }

        AppUser entity = new AppUser();

        entity.setId(dto.id());
        entity.setUsername(dto.username());
        entity.setEmail(dto.email());
        entity.setRole(dto.role());

        return entity;
    }

    public AppUserDTO toDto(AppUser entity) {
        if (entity == null) {
            return null;
        }

        return new AppUserDTO(entity.getId(),
                entity.getUsername(),
                entity.getEmail(),
                entity.getRole());
    }
}

//Generated by Sprout