package org.aminesidki.postprep.mapper;

import org.aminesidki.postprep.entity.AppUser;
import org.aminesidki.postprep.dto.AppUserDTO;
import org.aminesidki.postprep.entity.Article;
import org.aminesidki.postprep.exception.NotFoundException;
import org.aminesidki.postprep.repository.ArticleRepository;
import org.springframework.stereotype.Component;
import lombok.RequiredArgsConstructor;

import java.util.ArrayList;
import java.util.UUID;

/**
* Mapper for {@link org.aminesidki.postprep.entity.AppUser }
*/
@Component
@RequiredArgsConstructor
public class AppUserMapper {
    private final ArticleRepository articleRepository;

    public AppUser toEntity(AppUserDTO dto) {
        if (dto == null) {
            return null;
        }

        AppUser entity = new AppUser();

        entity.setId(dto.getId());
        entity.setUsername(dto.getUsername());
        entity.setEmail(dto.getEmail());
        entity.setRole(dto.getRole());

        if(dto.getArticles() != null ) {
            entity.setArticles(new ArrayList<>());
            for(UUID id : dto.getArticles()){
                entity.getArticles().add(articleRepository.findById(id).orElseThrow(() -> new NotFoundException("Article with id " + id + "not found !")));
            }
        }
        return entity;
    }

    public AppUserDTO toDto(AppUser entity) {
        if (entity == null) {
            return null;
        }

        AppUserDTO dto = new AppUserDTO();

        dto.setId(entity.getId());
        dto.setUsername(entity.getUsername());
        dto.setEmail(entity.getEmail());
        dto.setRole(entity.getRole());

        if(entity.getArticles() != null){
            dto.setArticles(new ArrayList<>());
            for(Article a : entity.getArticles()){
                dto.getArticles().add(a.getId());
            }
        }

        return dto;
    }
}

//Generated by Sprout