package org.aminesidki.postprep.mapper;

import org.aminesidki.postprep.entity.AppUser;
import org.aminesidki.postprep.dto.AppUserDTO;
import org.springframework.stereotype.Component;
import lombok.RequiredArgsConstructor;

import java.util.UUID;
import org.aminesidki.postprep.repository.RoleRepository;

/**
* Mapper for {@link org.aminesidki.postprep.entity.AppUser }
*/
@Component
@RequiredArgsConstructor
public class AppUserMapper {
    private final RoleRepository roleRepo;

    public AppUser toEntity(AppUserDTO dto) {
        if (dto == null) {
            return null;
        }

        AppUser entity = new AppUser();

        entity.setId(dto.getId());
        entity.setUsername(dto.getUsername());
        entity.setEmail(dto.getEmail());
        entity.setPassword(dto.getPassword());

        if (dto.getRole() != null) {
            entity.setRole(roleRepo.findByRoleTitle(dto.getRole().toUpperCase()).orElseThrow(() -> new RuntimeException("Role not found !")));
        }

        return entity;
    }

    public AppUserDTO toDto(AppUser entity) {
        if (entity == null) {
            return null;
        }

        AppUserDTO dto = new AppUserDTO();

        dto.setId(entity.getId());
        dto.setUsername(entity.getUsername());
        dto.setEmail(entity.getEmail());
        dto.setPassword(entity.getPassword());

        if (entity.getRole() != null) {
            dto.setRole(entity.getRole().getRoleTitle());
        }

        return dto;
    }
}

//Generated by Sprout