package org.aminesidki.postprep.mapper;

import org.aminesidki.postprep.entity.Article;
import org.aminesidki.postprep.dto.ArticleDTO;
import org.springframework.stereotype.Component;
import lombok.RequiredArgsConstructor;

import java.sql.Timestamp;
import java.util.UUID;

/**
* Mapper for {@link org.aminesidki.postprep.entity.Article }
*/
@Component
@RequiredArgsConstructor
public class ArticleMapper {

    public Article toEntity(ArticleDTO dto) {
        if (dto == null) {
            return null;
        }

        Article entity = new Article();

        entity.setId(dto.getId());
        entity.setTitle(dto.getTitle());
        entity.setContent(dto.getContent());
        entity.setLanguage(dto.getLanguage());
        entity.setCreatedAt(dto.getCreatedAt());


        return entity;
    }

    public ArticleDTO toDto(Article entity) {
        if (entity == null) {
            return null;
        }

        ArticleDTO dto = new ArticleDTO();

        dto.setId(entity.getId());
        dto.setTitle(entity.getTitle());
        dto.setContent(entity.getContent());
        dto.setLanguage(entity.getLanguage());
        dto.setCreatedAt(entity.getCreatedAt());


        return dto;
    }
}

//Generated by Sprout