package org.aminesidki.postprep.mapper;

import org.aminesidki.postprep.entity.Article;
import org.aminesidki.postprep.dto.regular.ArticleDTO;
import org.aminesidki.postprep.exception.NotFoundException;
import org.aminesidki.postprep.repository.AppUserRepository;
import org.springframework.stereotype.Component;
import lombok.RequiredArgsConstructor;

import java.util.Objects;


/**
* Mapper for {@link org.aminesidki.postprep.entity.Article }
*/
@Component
@RequiredArgsConstructor
public class ArticleMapper {
    private final AppUserRepository appUserRepository;
    public Article toEntity(ArticleDTO dto) {
        if (dto == null) {
            return null;
        }

        Article entity = new Article();

        entity.setId(dto.id());
        entity.setTitle(dto.title());
        entity.setLanguage(dto.language());
        entity.setOwner(Objects.requireNonNull(appUserRepository.getReferenceById(dto.owner())));
        entity.setOutputJson(dto.outputJson());
        entity.setStatus(dto.status());
        entity.setCreatedAt(dto.createdAt());


        return entity;
    }

    public ArticleDTO toDto(Article entity) {
        if (entity == null) {
            return null;
        }

        return new ArticleDTO(entity.getId(),
                entity.getTitle(),
                entity.getLanguage(),
                entity.getOwner().getId(),
                entity.getStatus(),
                entity.getOutputJson(),
                entity.getCreatedAt());
    }
}

//Generated by Sprout