package org.aminesidki.postprep.mapper;

import org.aminesidki.postprep.entity.JsonOutput;
import org.aminesidki.postprep.dto.JsonOutputDTO;
import org.springframework.stereotype.Component;
import lombok.RequiredArgsConstructor;

import java.util.List;
import java.util.UUID;

/**
* Mapper for {@link org.aminesidki.postprep.entity.JsonOutput }
*/
@Component
@RequiredArgsConstructor
public class JsonOutputMapper {

    public JsonOutput toEntity(JsonOutputDTO dto) {
        if (dto == null) {
            return null;
        }

        JsonOutput entity = new JsonOutput();

        entity.setId(dto.getId());
        entity.setSummary(dto.getSummary());
        entity.setCategory(dto.getCategory());
        entity.setSeoTitle(dto.getSeoTitle());
        entity.setConfidenceScore(dto.getConfidenceScore());
        entity.setKeywords(dto.getKeywords());


        return entity;
    }

    public JsonOutputDTO toDto(JsonOutput entity) {
        if (entity == null) {
            return null;
        }

        JsonOutputDTO dto = new JsonOutputDTO();

        dto.setId(entity.getId());
        dto.setSummary(entity.getSummary());
        dto.setCategory(entity.getCategory());
        dto.setSeoTitle(entity.getSeoTitle());
        dto.setConfidenceScore(entity.getConfidenceScore());
        dto.setKeywords(entity.getKeywords());


        return dto;
    }
}

//Generated by Sprout