package org.aminesidki.postprep.mapper;

import org.aminesidki.postprep.entity.AppUser;
import org.aminesidki.postprep.entity.Role;
import org.aminesidki.postprep.dto.RoleDTO;
import org.springframework.stereotype.Component;
import lombok.RequiredArgsConstructor;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.UUID;
import org.aminesidki.postprep.repository.AppUserRepository;

/**
* Mapper for {@link org.aminesidki.postprep.entity.Role }
*/
@Component
@RequiredArgsConstructor
public class RoleMapper {
    private final AppUserRepository appuserRepo;

    public Role toEntity(RoleDTO dto) {
        if (dto == null) {
            return null;
        }

        Role entity = new Role();

        entity.setId(dto.getId());
        entity.setRoleTitle(dto.getRoleTitle());

        // Mapping association: Users
        if (dto.getUsers() != null) {
            entity.setUsers(new ArrayList<>());
            for(UUID id : dto.getUsers()) {
                entity.getUsers().add(appuserRepo.findById(id).orElse(null));
            }
        }

        return entity;
    }

    public RoleDTO toDto(Role entity) {
        if (entity == null) {
            return null;
        }

        RoleDTO dto = new RoleDTO();

        dto.setId(entity.getId());
        dto.setRoleTitle(entity.getRoleTitle());

        if (entity.getUsers() != null) {
            dto.setUsers(new HashSet<>());
            for(AppUser sub : entity.getUsers()) {
                dto.getUsers().add(sub.getId());
            }
        }

        return dto;
    }
}

//Generated by Sprout