package org.aminesidki.postprep.dto.regular;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotEmpty;
import org.aminesidki.postprep.enumeration.Role;

import java.io.Serializable;

import java.util.UUID;

/**
* DTO for {@link org.aminesidki.postprep.entity.AppUser }
*/
public record AppUserDTO(
        @JsonProperty(access = JsonProperty.Access.READ_ONLY)
        UUID id,
        @NotEmpty
        String username,
        @NotEmpty
        @Email
        String email,
        @NotEmpty
        @JsonProperty(access = JsonProperty.Access.READ_ONLY)
        Role role
) implements Serializable {}

//Generated by Sprout