package org.aminesidki.postprep.dto.regular;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.NotEmpty;
import lombok.*;
import org.aminesidki.postprep.entity.OutputJson;
import org.aminesidki.postprep.enumeration.Status;

import java.io.Serializable;

import java.sql.Timestamp;
import java.util.UUID;

/**
* DTO for {@link org.aminesidki.postprep.entity.Article }
*/
public record ArticleDTO (
        @JsonProperty(access = JsonProperty.Access.READ_ONLY)
        UUID id,
        @NotEmpty
        String title,
        @NotEmpty
        String language,
        @NotEmpty
        UUID owner,
        @NotEmpty
        Status status,
        @NotEmpty
        OutputJson outputJson,
        @NotEmpty
        Timestamp createdAt
) implements Serializable {}

//Generated by Sprout