package org.aminesidki.postprep.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotEmpty;
import lombok.*;
import org.aminesidki.postprep.enumeration.Role;

import java.io.Serializable;

import java.util.List;
import java.util.UUID;

/**
* DTO for {@link org.aminesidki.postprep.entity.AppUser }
*/
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class AppUserDTO implements Serializable {

    @EqualsAndHashCode.Include
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private UUID id;

    @NotEmpty
    private String username;
    @NotEmpty
    @Email
    private String email;
    @NotEmpty
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private Role role;

}

//Generated by Sprout