package org.aminesidki.postprep.dto;

import lombok.*;
import org.aminesidki.postprep.enumeration.Role;

import java.io.Serializable;

import java.util.List;
import java.util.UUID;

/**
* DTO for {@link org.aminesidki.postprep.entity.AppUser }
*/
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AppUserDTO implements Serializable {

    private UUID id;
    private String username;
    private String email;
    private Role role;

}

//Generated by Sprout