package org.aminesidki.postprep.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.NotEmpty;
import lombok.*;
import org.aminesidki.postprep.entity.OutputJson;
import org.aminesidki.postprep.enumeration.Status;

import java.io.Serializable;

import java.sql.Timestamp;
import java.util.UUID;

/**
* DTO for {@link org.aminesidki.postprep.entity.Article }
*/
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class ArticleDTO implements Serializable {

    @EqualsAndHashCode.Include
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private UUID id;
    @NotEmpty
    private String title;
    @NotEmpty
    private String language;
    @NotEmpty
    private UUID owner;
    @NotEmpty
    private Status status;
    @NotEmpty
    private OutputJson outputJson;
    @NotEmpty
    private Timestamp createdAt;

}

//Generated by Sprout