package org.aminesidki.postprep.dto;

import lombok.*;
import java.io.Serializable;

import java.sql.Timestamp;
import java.util.UUID;

/**
* DTO for {@link org.aminesidki.postprep.entity.Article }
*/
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ArticleDTO implements Serializable {

    private UUID id;
    private String title;
    private String content;
    private String language;
    private UUID owner;
    private Timestamp createdAt;

}

//Generated by Sprout