package org.aminesidki.postprep.dto;

import lombok.*;
import java.io.Serializable;

import java.util.List;
import java.util.UUID;

/**
* DTO for {@link org.aminesidki.postprep.entity.JsonOutput }
*/
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class JsonOutputDTO implements Serializable {

    private UUID id;
    private String summary;
    private String category;
    private String seoTitle;
    private Integer confidenceScore;
    private List<String> keywords;

}

//Generated by Sprout