package org.aminesidki.postprep.dto;

import lombok.*;
import java.io.Serializable;

import java.util.Set;
import java.util.UUID;

/**
* DTO for {@link org.aminesidki.postprep.entity.Role }
*/
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class RoleDTO implements Serializable {

    private Long id;
    private String roleTitle;
    private Set<UUID> users;

}

//Generated by Sprout