package org.aminesidki.postprep.repository;

import org.aminesidki.postprep.entity.AppUser;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.UUID;

/**
* Repository for {@link org.aminesidki.postprep.entity.AppUser }
*/
@Repository
public interface AppUserRepository extends JpaRepository<AppUser, UUID> {}

//Generated by Sprout