package org.aminesidki.postprep.repository;

import org.aminesidki.postprep.entity.AppUser;
import org.aminesidki.postprep.repository.projection.AuthInfo;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import java.util.Optional;
import java.util.UUID;

/**
* Repository for {@link org.aminesidki.postprep.entity.AppUser }
*/
@Repository
public interface AppUserRepository extends JpaRepository<AppUser, UUID> {
    @Query("SELECT u FROM AppUser u LEFT JOIN FETCH u.articles WHERE u.email = :email")
    Optional<AppUser> findByEmailWithArticles(@Param("email") String email);

    Optional<AppUser> findByEmail(String email);
    Optional<AppUser> findByRefreshToken(String refreshToken);

    Boolean existsByEmail(String email);
    Boolean existsByUsername(String username);

    @Modifying
    @Transactional
    @Query("UPDATE AppUser u SET u.refreshToken = NULL WHERE u.id = :userId")
    void invalidateRefreshToken(@Param("userId") UUID userId);

    Optional<AuthInfo> findAuthInfoByEmail(String email);
}

//Generated by Sprout