package org.aminesidki.postprep.repository;

import org.aminesidki.postprep.dto.ArticleDTO;
import org.aminesidki.postprep.entity.AppUser;
import org.aminesidki.postprep.entity.Article;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.sql.Timestamp;
import java.util.List;
import java.util.UUID;

/**
* Repository for {@link org.aminesidki.postprep.entity.Article }
*/
@Repository
public interface ArticleRepository extends JpaRepository<Article, UUID> {
    List<Article> findByOwner(AppUser user);
}

//Generated by Sprout