package org.aminesidki.postprep.repository;

import org.aminesidki.postprep.dto.LiteArticleDTO;
import org.aminesidki.postprep.entity.AppUser;
import org.aminesidki.postprep.entity.Article;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.sql.Timestamp;
import java.util.List;
import java.util.UUID;

/**
* Repository for {@link org.aminesidki.postprep.entity.Article }
*/
@Repository
public interface ArticleRepository extends JpaRepository<Article, UUID> {

    @Query(value = "SELECT TO_CHAR(created_at, 'YYYY-MM-DD') as dateLabel, COUNT(*) as count " +
            "FROM article " +
            "WHERE created_at >= :startDate " +
            "GROUP BY dateLabel " +
            "ORDER BY dateLabel ASC", nativeQuery = true)
    List<Object[]> countArticlesPerDay(@Param("startDate") Timestamp startDate);

    @Query(value = "SELECT TO_CHAR(created_at, 'YYYY-MM') as monthLabel, COUNT(*) as count " +
            "FROM article " +
            "WHERE created_at >= :startDate " +
            "GROUP BY monthLabel " +
            "ORDER BY monthLabel ASC", nativeQuery = true)
    List<Object[]> countArticlesPerMonth(@Param("startDate") Timestamp startDate);
}

//Generated by Sprout