package org.aminesidki.postprep.repository;

import org.aminesidki.postprep.entity.JsonOutput;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.UUID;

/**
* Repository for {@link org.aminesidki.postprep.entity.JsonOutput }
*/
@Repository
public interface JsonOutputRepository extends JpaRepository<JsonOutput, UUID> {}

//Generated by Sprout