package org.aminesidki.postprep.repository;

import org.aminesidki.postprep.entity.Role;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;


/**
* Repository for {@link org.aminesidki.postprep.entity.Role }
*/
@Repository
public interface RoleRepository extends JpaRepository<Role, Long> {
    Optional<Role> findByRoleTitle(String role);
}

//Generated by Sprout