package org.aminesidki.postprep.repository;

import org.aminesidki.postprep.entity.Role;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;


/**
* Repository for {@link org.aminesidki.postprep.entity.Role }
*/
@Repository
public interface RoleRepository extends JpaRepository<Role, Long> {}

//Generated by Sprout