package org.aminesidki.postprep.service;

import lombok.NonNull;
import org.aminesidki.postprep.dto.RegisterRequestDTO;
import org.aminesidki.postprep.entity.AppUser;
import org.aminesidki.postprep.dto.AppUserDTO;
import org.aminesidki.postprep.enumeration.Role;
import org.aminesidki.postprep.exception.NotFoundException;
import org.aminesidki.postprep.mapper.AppUserMapper;
import org.aminesidki.postprep.repository.AppUserRepository;

import lombok.RequiredArgsConstructor;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.stream.Collectors;

import java.util.UUID;

@RequiredArgsConstructor
@Service
public class AppUserService{
    private final AppUserRepository appUserRepository;
    private final AppUserMapper mapper;
    private final PasswordEncoder passwordEncoder;

    public AppUserDTO findById(UUID id) {
        return appUserRepository.findById(id)
                .map(mapper::toDto)
                .orElseThrow(() -> new NotFoundException("AppUser not found with id: " + id));
    }

    public List< AppUserDTO> findAll() {
        return appUserRepository.findAll().stream()
                .map(mapper::toDto)
                .collect(Collectors.toList());
    }

    public void delete(UUID id) {
        if (!appUserRepository.existsById(id)) {
            throw new NotFoundException("Cannot delete: AppUser not found with id: " + id);
        }
        appUserRepository.deleteById(id);
    }

    public AppUserDTO findByEmail(@NonNull String email) {
        return appUserRepository.findByEmail(email)
                .map(mapper::toDto)
                .orElseThrow(() -> new NotFoundException("AppUser not found with email: " + email));
    }

    public AppUser findUserByEmail(@NonNull String email) {
        return appUserRepository.findByEmail(email)
                .orElseThrow(() -> new NotFoundException("AppUser not found with email: " + email));
    }

    public void register(RegisterRequestDTO request) {
        String sanitizedEmail = request.getEmail().trim().toLowerCase();
        String sanitizedUsername = request.getUsername().trim();

        if (appUserRepository.existsByEmail(sanitizedEmail)) {
            throw new RuntimeException("Email already exists");
        }

        if (appUserRepository.existsByUsername(sanitizedUsername)) {
            throw new RuntimeException("Username already exists");
        }

        AppUser user = AppUser.builder()
                .username(sanitizedUsername)
                .email(sanitizedEmail)
                .password(passwordEncoder.encode(request.getPassword()))
                .role(Role.USER)
                .build();

        appUserRepository.save(user);
    }

    public AppUser findByRefreshToken(String refreshToken) {
        return appUserRepository.findByRefreshToken(refreshToken)
                .orElseThrow(() -> new NotFoundException("User not found"));
    }

    public void updateRefreshToken(String email, String token) {
        AppUser appUser = findUserByEmail(email);
        appUser.setRefreshToken(token);
        appUserRepository.save(appUser);
    }

    public void logout(UUID userId) {
        appUserRepository.invalidateRefreshToken(userId);
    }

    public long  count() {
        return appUserRepository.count();
    }

    @Transactional
    public AppUserDTO updateUser(UUID id, AppUserDTO dto) {
        AppUser user = appUserRepository.findById(id)
                .orElseThrow(() -> new NotFoundException("User not found with id: " + id));

        String newUsername = dto.getUsername().trim();

        if (!user.getUsername().equals(newUsername)) {
            if (appUserRepository.existsByUsername(newUsername)) {
                throw new RuntimeException("Username already exists");
            }
            user.setUsername(newUsername);
        }

        String newEmail = dto.getEmail().trim().toLowerCase();

        if (!user.getEmail().equalsIgnoreCase(newEmail)) {
            validateEmailUniqueness(newEmail);
            user.setEmail(newEmail);
        }

        return mapper.toDto(appUserRepository.save(user));
    }

    private void validateEmailUniqueness(String email) {
        if (appUserRepository.existsByEmail(email)) {
            throw new RuntimeException("Email already exists");
        }
    }

}

//Generated by Sprout