package org.aminesidki.postprep.service;

import lombok.NonNull;
import org.aminesidki.postprep.dto.RegisterRequestDTO;
import org.aminesidki.postprep.entity.AppUser;
import org.aminesidki.postprep.dto.AppUserDTO;
import org.aminesidki.postprep.enumeration.Role;
import org.aminesidki.postprep.exception.NotFoundException;
import org.aminesidki.postprep.mapper.AppUserMapper;
import org.aminesidki.postprep.repository.AppUserRepository;

import lombok.RequiredArgsConstructor;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.stream.Collectors;

import java.util.UUID;

@RequiredArgsConstructor
@Service
public class AppUserService{
    private final AppUserRepository repository;
    private final AppUserMapper mapper;
    private final PasswordEncoder passwordEncoder;

    public AppUserDTO findById(UUID id) {
        return repository.findById(id)
                .map(mapper::toDto)
                .orElseThrow(() -> new RuntimeException("AppUser not found with id: " + id));
    }

    public List< AppUserDTO> findAll() {
        return repository.findAll().stream()
                .map(mapper::toDto)
                .collect(Collectors.toList());
    }

    @Transactional
    public AppUserDTO save(AppUserDTO dto) {
        AppUser entity = mapper.toEntity(dto);
        return mapper.toDto(repository.save(entity));
    }

    @Transactional
    public void delete(UUID id) {
        if (!repository.existsById(id)) {
            throw new RuntimeException("Cannot delete: AppUser not found with id: " + id);
        }
        repository.deleteById(id);
    }


    public AppUserDTO findByEmail(@NonNull String email) {
        return repository.findByEmail(email)
                .map(mapper::toDto)
                .orElseThrow(() -> new RuntimeException("AppUser not found with email: " + email));
    }

    public AppUserDTO findByEmailWithArticles(@NonNull String email){
        return repository.findByEmailWithArticles(email)
                .map(mapper::toDto)
                .orElseThrow(() -> new RuntimeException("AppUser not found with email: " + email));
    }

    @Transactional
    public void register(RegisterRequestDTO request) {
        if (repository.existsByEmail(request.getEmail())) {
            throw new RuntimeException("Email already exists");
        }

        AppUser user = new AppUser();
        user.setUsername(request.getUsername());
        user.setEmail(request.getEmail());
        user.setPassword(passwordEncoder.encode(request.getPassword()));
        user.setRole(Role.USER);

        repository.save(user);
    }

    public AppUser findByRefreshToken(String refreshToken) {
        return repository.findByRefreshToken(refreshToken)
                .orElseThrow(() -> new NotFoundException("User not found"));
    }

    public void updateRefreshToken(String email, String token) {
        AppUser appUser = mapper.toEntity(findByEmail(email));
        appUser.setRefreshToken(token);
        repository.save(appUser);
    }

    public void logout(UUID userId) {
        repository.invalidateRefreshToken(userId);
    }
}

//Generated by Sprout