package org.aminesidki.postprep.service;

import org.aminesidki.postprep.entity.AppUser;
import org.aminesidki.postprep.dto.AppUserDTO;
import org.aminesidki.postprep.mapper.AppUserMapper;
import org.aminesidki.postprep.repository.AppUserRepository;

import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.stream.Collectors;
import java.util.Optional;

import java.util.UUID;

@RequiredArgsConstructor
@Service
public class AppUserService{
    private final AppUserRepository repository;
    private final AppUserMapper mapper;

    public AppUserDTO findById(UUID id) {
        return repository.findById(id)
                .map(mapper::toDto)
                .orElseThrow(() -> new RuntimeException("AppUser not found with id: " + id));
    }

    public List< AppUserDTO> findAll() {
        return repository.findAll().stream()
                .map(mapper::toDto)
                .collect(Collectors.toList());
    }

    @Transactional
    public AppUserDTO save(AppUserDTO dto) {
        AppUser entity = mapper.toEntity(dto);
        return mapper.toDto(repository.save(entity));
    }

    @Transactional
    public void delete(UUID id) {
        if (!repository.existsById(id)) {
            throw new RuntimeException("Cannot delete: AppUser not found with id: " + id);
        }
        repository.deleteById(id);
    }
}

//Generated by Sprout