package org.aminesidki.postprep.service;

import org.aminesidki.postprep.dto.AppUserDTO;
import org.aminesidki.postprep.dto.LiteArticleDTO;
import org.aminesidki.postprep.dto.ChartDataDTO;
import org.aminesidki.postprep.entity.Article;
import org.aminesidki.postprep.dto.ArticleDTO;
import org.aminesidki.postprep.exception.NotFoundException;
import org.aminesidki.postprep.mapper.AppUserMapper;
import org.aminesidki.postprep.mapper.ArticleMapper;
import org.aminesidki.postprep.mapper.LiteArticleMapper;
import org.aminesidki.postprep.repository.ArticleRepository;

import lombok.RequiredArgsConstructor;
import org.aminesidki.postprep.repository.LiteArticleRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

import java.util.UUID;

@RequiredArgsConstructor
@Service
@Transactional
public class ArticleService{
    private final ArticleRepository repository;
    private final ArticleMapper articleMapper;
    private final LiteArticleRepository liteArticleRepository;
    private final AppUserMapper userMapper;

    public ArticleDTO findById(UUID id) {
        return repository.findById(id)
                .map(articleMapper::toDto)
                .orElseThrow(() -> new NotFoundException("Article not found with id: " + id));
    }

    public List< ArticleDTO> findAll() {
        return repository.findAll().stream()
                .map(articleMapper::toDto)
                .collect(Collectors.toList());
    }

    public List<LiteArticleDTO> findAllByOwner(AppUserDTO owner) {
        return liteArticleRepository.findByOwner(userMapper.toEntity(owner));
    }

    public ArticleDTO save(ArticleDTO dto) {
        Article entity = articleMapper.toEntity(dto);
        return articleMapper.toDto(repository.save(entity));
    }

    public boolean delete(AppUserDTO user , UUID id) {
        if(!repository.findById(id).orElseThrow(() -> new NotFoundException("Cannot delete: Article not found with id " + id))
                .getOwner()
                .getId().equals(user.getId())){
            return false;
        }
        repository.deleteById(id);
        return true;
    }

    public void deleteById(UUID id) {
        repository.deleteById(id);
    }

    public long  count() {
        return repository.count();
    }

    public List<ChartDataDTO> getDailyArticleStats() {
        LocalDateTime thirtyDaysAgo = LocalDateTime.now().minusDays(30);
        Timestamp startDate = Timestamp.valueOf(thirtyDaysAgo);

        List<Object[]> rawData = repository.countArticlesPerDay(startDate);

        return mapToDTO(rawData);
    }

    public List<ChartDataDTO> getMonthlyArticleStats() {
        LocalDateTime oneYearAgo = LocalDateTime.now().minusMonths(12);
        Timestamp startDate = Timestamp.valueOf(oneYearAgo);

        List<Object[]> rawData = repository.countArticlesPerMonth(startDate);

        return mapToDTO(rawData);
    }

    private List<ChartDataDTO> mapToDTO(List<Object[]> rawData) {
        return rawData.stream()
                .map(row -> new ChartDataDTO(
                        (String) row[0],                // Cast du Label (Date)
                        ((Number) row[1]).longValue()   // Cast sécurisé du Count (BigInt -> Long)
                ))
                .collect(Collectors.toList());
    }




}

//Generated by Sprout