package org.aminesidki.postprep.service;

import org.aminesidki.postprep.dto.AppUserDTO;
import org.aminesidki.postprep.entity.Article;
import org.aminesidki.postprep.dto.ArticleDTO;
import org.aminesidki.postprep.mapper.AppUserMapper;
import org.aminesidki.postprep.mapper.ArticleMapper;
import org.aminesidki.postprep.repository.ArticleRepository;

import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import java.util.UUID;

@RequiredArgsConstructor
@Service
public class ArticleService{
    private final ArticleRepository repository;
    private final ArticleMapper articleMapper;
    private final AppUserMapper userMapper;

    @Transactional
    public ArticleDTO findById(UUID id) {
        return repository.findById(id)
                .map(articleMapper::toDto)
                .orElseThrow(() -> new RuntimeException("Article not found with id: " + id));
    }

    @Transactional
    public List< ArticleDTO> findAll() {
        return repository.findAll().stream()
                .map(articleMapper::toDto)
                .collect(Collectors.toList());
    }

    @Transactional
    public List<ArticleDTO> findAllByOwner(AppUserDTO owner){
        return repository.findByOwner(userMapper.toEntity(owner)).stream()
                .map(articleMapper::toDto)
                .collect(Collectors.toList());
    }

    @Transactional
    public ArticleDTO save(ArticleDTO dto) {
        Article entity = articleMapper.toEntity(dto);
        return articleMapper.toDto(repository.save(entity));
    }

    @Transactional
    public boolean delete(AppUserDTO user , UUID id) {
        if (!repository.existsById(id)) {
            throw new RuntimeException("Cannot delete: Article not found with id: " + id);
        }

        if(repository.findById(id).get().getOwner().getId() != user.getId()){
            return false;
        }
        repository.deleteById(id);
        return true;
    }

    @Transactional
    public void deleteById(UUID id) {
        repository.deleteById(id);
    }

    public long  count() {
        return repository.count();
    }

}

//Generated by Sprout