package org.aminesidki.postprep.service;

import org.aminesidki.postprep.entity.JsonOutput;
import org.aminesidki.postprep.dto.JsonOutputDTO;
import org.aminesidki.postprep.mapper.JsonOutputMapper;
import org.aminesidki.postprep.repository.JsonOutputRepository;

import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.stream.Collectors;
import java.util.Optional;

import java.util.UUID;

@RequiredArgsConstructor
@Service
public class JsonOutputService{
    private final JsonOutputRepository repository;
    private final JsonOutputMapper mapper;

    public JsonOutputDTO findById(UUID id) {
        return repository.findById(id)
                .map(mapper::toDto)
                .orElseThrow(() -> new RuntimeException("JsonOutput not found with id: " + id));
    }

    public List< JsonOutputDTO> findAll() {
        return repository.findAll().stream()
                .map(mapper::toDto)
                .collect(Collectors.toList());
    }

    @Transactional
    public JsonOutputDTO save(JsonOutputDTO dto) {
        JsonOutput entity = mapper.toEntity(dto);
        return mapper.toDto(repository.save(entity));
    }

    @Transactional
    public void delete(UUID id) {
        if (!repository.existsById(id)) {
            throw new RuntimeException("Cannot delete: JsonOutput not found with id: " + id);
        }
        repository.deleteById(id);
    }
}

//Generated by Sprout