package org.aminesidki.postprep.service;

import org.aminesidki.postprep.entity.Role;
import org.aminesidki.postprep.dto.RoleDTO;
import org.aminesidki.postprep.mapper.RoleMapper;
import org.aminesidki.postprep.repository.RoleRepository;

import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.stream.Collectors;
import java.util.Optional;


@RequiredArgsConstructor
@Service
public class RoleService{
    private final RoleRepository repository;
    private final RoleMapper mapper;

    public RoleDTO findById(Long id) {
        return repository.findById(id)
                .map(mapper::toDto)
                .orElseThrow(() -> new RuntimeException("Role not found with id: " + id));
    }

    public List< RoleDTO> findAll() {
        return repository.findAll().stream()
                .map(mapper::toDto)
                .collect(Collectors.toList());
    }

    @Transactional
    public RoleDTO save(RoleDTO dto) {
        Role entity = mapper.toEntity(dto);
        return mapper.toDto(repository.save(entity));
    }

    @Transactional
    public void delete(Long id) {
        if (!repository.existsById(id)) {
            throw new RuntimeException("Cannot delete: Role not found with id: " + id);
        }
        repository.deleteById(id);
    }

    public RoleDTO findByName(String name) {
        return repository.findByRoleTitle(name)
                .map(mapper::toDto)
                .orElseThrow(() -> new RuntimeException("Role not found with roleTitle: " + name));
    }
}

//Generated by Sprout